# Construct the build environment
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY . .

# Download dependencies and package the application, skipping tests
RUN mvn clean package -DskipTests -Pdocker

# Execute the application
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /app/target/*.war app.war

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.war", "--spring.profiles.active=docker"]
