spring:
  application:
    name: JoParis2024
  datasource:
    url: jdbc:mariadb://mysql-pchab.alwaysdata.net/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
JoParis2024:
  security:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 1 heure en millisecondes
