spring:
  application:
    name: JoParis2024
  datasource:
    url: jdbc:mariadb://mysql-pchab.alwaysdata.net/${DB_NAME}
    password: ^N.m*"J2c4j-T!C
    username: pchab_joparis
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
JoParis2024:
  security:
    secret: mBurFGsvfXBeLmyzhLD4syweo0L4j673Zo47ksREMLSP
    expiration: 3600000 # 1 heure en millisecondes
