spring:
    application:
        name: JoParis2024
    datasource:
        url: jdbc:mariadb://mysql-pchab.alwaysdata.net/pchab_joparis
        password: ${DB_PASSWORD}
        username: ${DB_USER}
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
logging:
    level:
        org.hibernate.type.descriptor.sql: DEBUG
        org.hibernate.type.descriptor.java: DEBUG
JoParis2024:
    security:
        secret: ${JWT_SECRET}
        expiration: 3600000 # 1 heure en millisecondes
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /v3/swagger-ui.html
stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    publicKey: ${STRIPE_PUBLIC_KEY}
    domain: ${STRIPE_DOMAIN}
