spring:
  application:
    name: JoParis2024
  datasource:
    url: jdbc:mariadb://mysql-pchab.alwaysdata.net/pchab_joparis
    password: ^N.m*"J2c4j-T!C
    username: pchab_joparis
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
logging:
  level:
    org.hibernate.type.descriptor.sql: DEBUG
    org.hibernate.type.descriptor.java: DEBUG
JoParis2024:
  security:
    secret: mySecretKeyForJWTGeneration
    expiration: 3600000 # 1 heure en millisecondes
